#!/bin/bash
set -e
cd $(dirname -- "$1")
INPUT_BASENAME=$(basename -- "$1")
cp "$INPUT_BASENAME.java" Main.java
javac -cp jars/parseq-3.0.2.jar Main.java
java -cp .:jars/parseq-3.0.2.jar:jars/slf4j-api-1.7.25.jar:jars/slf4j-log4j12-1.7.25.jar:jars/log4j-1.2.17.jar Main
